# Shared by new-assignment.R and import-assignment.R.
#
# assignments/_template/assignment.Rmd is the single place the YAML header and
# the setup chunk live. Change knitr options, the theme or the seed there and
# both scripts pick it up.
#
# Placeholders the template understands:
#   {{TITLE}}      the document title
#   {{AUTHOR}}     the author
#   {{LIBRARIES}}  one library() call per package
#   {{BODY}}       everything after this line is the starter body; the
#                  importer replaces it with the exercises it extracted,
#                  new-assignment.R keeps it as a worked example
#
# Run from the repository root.

# This code is generated by LLM.

TEMPLATE <- file.path("assignments", "_template", "assignment.Rmd")
AUTHOR <- "Mariia Steeghs-Turchina"

# Replace the single line equal to `marker` with `lines`.
splice_marker <- function(text, marker, lines) {
  i <- which(trimws(text) == marker)
  if (length(i) != 1L) {
    stop("Expected exactly one '", marker, "' line in '", TEMPLATE,
         "'; found ", length(i), ".", call. = FALSE)
  }
  c(
    if (i > 1L) text[seq_len(i - 1L)],
    lines,
    if (i < length(text)) text[(i + 1L):length(text)]
  )
}

# Render the template into the lines of a finished document.
#
#   title      goes into the YAML header
#   libraries  character vector of package names for the setup chunk
#   body       lines to use instead of the template's starter body, or NULL
#              to keep it
render_template <- function(title,
                            libraries = "tidyverse",
                            body = NULL,
                            author = AUTHOR,
                            template = TEMPLATE) {
  if (!file.exists(template)) {
    stop("Template not found at '", template, "'.", call. = FALSE)
  }

  text <- readLines(template, warn = FALSE)
  text <- gsub("{{TITLE}}", title, text, fixed = TRUE)
  text <- gsub("{{AUTHOR}}", author, text, fixed = TRUE)
  text <- splice_marker(text, "{{LIBRARIES}}", sprintf("library(%s)", libraries))

  i <- which(trimws(text) == "{{BODY}}")
  if (length(i) != 1L) {
    stop("Expected exactly one '{{BODY}}' line in '", template,
         "'; found ", length(i), ".", call. = FALSE)
  }

  if (is.null(body)) {
    text[-i]                      # keep the template's own starter body
  } else {
    c(text[seq_len(i - 1L)], body)
  }
}
