#!/usr/bin/env Rscript
# Build output/index.html: a plain list linking to each rendered assignment
# and its .Rmd source on GitHub. Run after scripts/render.R.
#
#   Rscript scripts/build-index.R
#
# Run from the repository root.

# This code is generated by LLM.

if (!dir.exists("assignments")) {
  stop("Run this from the repository root (no 'assignments/' directory here).", call. = FALSE)
}

# In GitHub Actions these are already set; locally, fall back to git so a
# preview build still gets working source links.
repo_slug <- Sys.getenv("GITHUB_REPOSITORY", "")
if (!nzchar(repo_slug)) {
  remote <- suppressWarnings(system2("git", c("remote", "get-url", "origin"), stdout = TRUE, stderr = FALSE))
  m <- regmatches(remote, regexec("github\\.com[:/]([^/]+/[^/]+?)(\\.git)?$", remote))[[1]]
  if (length(m) >= 2L) repo_slug <- m[[2]]
}
branch <- Sys.getenv("GITHUB_REF_NAME", "main")

ids <- list.dirs("assignments", full.names = FALSE, recursive = FALSE)
ids <- sort(ids[!startsWith(ids, "_")])
ids <- ids[file.exists(file.path("assignments", ids, paste0(ids, ".Rmd")))]

read_title <- function(id) {
  lines <- readLines(file.path("assignments", id, paste0(id, ".Rmd")), n = 20, warn = FALSE)
  m <- regmatches(lines, regexec('^title:\\s*"?([^"]+)"?\\s*$', lines))
  hit <- Filter(function(x) length(x) > 1L, m)
  if (length(hit) > 0L) hit[[1]][[2]] else id
}

esc <- function(x) gsub("<", "&lt;", gsub("&", "&amp;", x, fixed = TRUE), fixed = TRUE)

li <- function(id) {
  sprintf(
    '  <li>%s &mdash; <a href="%s.html">rendered</a> / <a href="https://github.com/%s/blob/%s/assignments/%s/%s.Rmd">source</a></li>',
    esc(read_title(id)), id, repo_slug, branch, id, id
  )
}

items <- if (length(ids) > 0L) {
  paste(vapply(ids, li, character(1)), collapse = "\n")
} else {
  "  <li>No assignments yet.</li>"
}

html <- sprintf('<!doctype html>
<meta charset="utf-8">
<title>BDS Toolbox</title>
<h1>BDS Toolbox</h1>
<ul>
%s
</ul>
', items)

dir.create("output", showWarnings = FALSE)
con <- file(file.path("output", "index.html"), open = "wb")
writeLines(enc2utf8(html), con, useBytes = TRUE)
close(con)

message("Created output/index.html (", length(ids), " assignment(s))")
