#!/usr/bin/env Rscript
# Turn a course handout into an assignment scaffold.
#
#   Rscript scripts/import-assignment.R <handout> <id> [title]
#
#   Rscript scripts/import-assignment.R ~/Downloads/R4DS-Ass1-Explore.html 01-explore
#
# <handout> is the knitted HTML the course publishes.
#
# What comes out is assignments/<id>/<id>.Rmd: the questions as headings, an
# empty named chunk under each one, any code or figures the handout supplied,
# and a setup chunk loading the packages the handout uses. Answers are left
# for you -- this only ever copies the questions across.
#
# Run from the repository root.

# This code is generated by LLM.

AUTHOR <- "Mariia Steeghs-Turchina"

# A heading that names an exercise: "3.2.4", "5.2.4: 1", "Exercise 19.4.4".
EXERCISE_HEADING <- "^\\s*(exercise|question|ex\\.?|q\\.?)?\\s*[0-9]+(\\.[0-9]+)*\\s*(:\\s*[0-9]+)?\\s*$"

# ---------------------------------------------------------------- arguments

args <- commandArgs(trailingOnly = TRUE)

if (length(args) < 2L) {
  stop("Usage: Rscript scripts/import-assignment.R <handout> <id> [title]", call. = FALSE)
}
if (!dir.exists("assignments")) {
  stop("Run this from the repository root (no 'assignments/' directory here).", call. = FALSE)
}

handout <- args[[1]]
id <- args[[2]]
title_arg <- if (length(args) > 2L) args[[3]] else NA_character_

if (!file.exists(handout)) {
  stop("No handout at '", handout, "'.", call. = FALSE)
}

target <- file.path("assignments", id, paste0(id, ".Rmd"))
fig_dir <- file.path("assignments", id, "figures")

if (file.exists(target)) {
  stop("'", target, "' already exists -- delete it first if you really mean to start over.", call. = FALSE)
}

# ------------------------------------------------------------------ reading

if (!tolower(tools::file_ext(handout)) %in% c("html", "htm")) {
  stop("'", handout, "' is not HTML. Save the handout as HTML and import that.", call. = FALSE)
}

doc <- xml2::read_html(handout, encoding = "UTF-8")

# Blocks in reading order. Nested matches are dropped, so a paragraph inside a
# list is covered by the list and never seen twice.
blocks <- local({
  found <- xml2::xml_find_all(
    doc,
    ".//h1|.//h2|.//h3|.//h4|.//h5|.//h6|.//p|.//ol|.//ul|.//pre|.//blockquote"
  )
  paths <- vapply(found, xml2::xml_path, character(1))

  keep <- rep(TRUE, length(found))
  for (i in seq_along(found)) {
    if (!keep[[i]]) next
    inside <- startsWith(paths, paste0(paths[[i]], "/"))
    keep[inside] <- FALSE
  }
  found[keep]
})

# --------------------------------------------------------------- extraction

# Inline <code> survives as markdown backticks; block code is left alone.
as_markdown <- function(node) {
  # Re-parse a copy so the backticks below don't mutate the source document.
  # read_html rather than read_xml, because handouts are full of <img> and <br>.
  frag <- xml2::read_html(paste0("<div>", as.character(node), "</div>"))
  root <- xml2::xml_find_first(frag, ".//div")

  for (cn in xml2::xml_find_all(root, ".//code[not(ancestor::pre)]")) {
    xml2::xml_text(cn) <- paste0("`", xml2::xml_text(cn), "`")
  }
  txt <- xml2::xml_text(root)
  txt <- gsub("\u00a0", " ", txt, fixed = TRUE)   # knitted handouts are full of these
  trimws(gsub("[[:space:]]+", " ", txt))
}

node_name <- function(node) tolower(xml2::xml_name(node))

heading_level <- function(node) {
  nm <- node_name(node)
  if (grepl("^h[1-6]$", nm)) as.integer(substring(nm, 2)) else NA_integer_
}

# List items, each as one line of markdown. Paragraphs inside an item are
# joined with a space rather than run together.
list_items <- function(node) {
  vapply(xml2::xml_find_all(node, "./li"), function(li) {
    paras <- xml2::xml_find_all(li, "./p")
    if (length(paras) > 0L) {
      paste(vapply(paras, as_markdown, character(1)), collapse = " ")
    } else {
      as_markdown(li)
    }
  }, character(1))
}

# Base64 images are written out; images already on disk are copied in.
save_images <- function(node, slug, counter) {
  srcs <- xml2::xml_attr(xml2::xml_find_all(node, ".//img"), "src")
  srcs <- srcs[!is.na(srcs)]
  out <- character()

  for (src in srcs) {
    m <- regmatches(src, regexec("^data:image/([a-zA-Z+]+);base64,(.*)$", src))[[1]]

    if (length(m) == 3L) {
      ext <- sub("\\+xml$", "", m[[2]])
      name <- sprintf("%s-%d.%s", slug, counter(), ext)
      dir.create(fig_dir, recursive = TRUE, showWarnings = FALSE)
      writeBin(base64enc::base64decode(m[[3]]), file.path(fig_dir, name))
      out <- c(out, name)
    } else if (!grepl("^(https?|data):", src)) {
      from <- file.path(dirname(handout), src)
      if (file.exists(from)) {
        name <- sprintf("%s-%d.%s", slug, counter(), tools::file_ext(src))
        dir.create(fig_dir, recursive = TRUE, showWarnings = FALSE)
        file.copy(from, file.path(fig_dir, name), overwrite = TRUE)
        out <- c(out, name)
      }
    }
  }
  out
}

# ------------------------------------------------------------------ sectioning

headings <- vapply(blocks, function(b) {
  if (is.na(heading_level(b))) "" else as_markdown(b)
}, character(1))

is_exercise <- grepl(EXERCISE_HEADING, headings) & nzchar(headings)

# Nothing looks like an exercise number? Fall back to the most common heading
# level, so an unfamiliar handout still produces something usable.
if (!any(is_exercise)) {
  levels_seen <- vapply(blocks, heading_level, integer(1))
  levels_seen <- levels_seen[!is.na(levels_seen)]
  if (length(levels_seen) > 0L) {
    common <- as.integer(names(sort(table(levels_seen), decreasing = TRUE))[[1]])
    is_exercise <- vapply(blocks, heading_level, integer(1)) == common
    is_exercise[is.na(is_exercise)] <- FALSE
  }
  message("No exercise-style headings found; splitting on every level-",
          if (exists("common")) common else "?", " heading instead.")
}

if (!any(is_exercise)) {
  stop("Could not find any headings to split '", handout, "' into exercises.", call. = FALSE)
}

first <- which(is_exercise)[[1]]
intro_blocks <- if (first > 1L) blocks[seq_len(first - 1L)] else list()
section_start <- which(is_exercise)
section_end <- c(section_start[-1] - 1L, length(blocks))

# ----------------------------------------------------------------- metadata

doc_title <- if (!is.na(title_arg)) {
  title_arg
} else {
  h1 <- xml2::xml_find_first(doc, ".//h1")
  if (!inherits(h1, "xml_missing")) as_markdown(h1) else id
}

doc_author <- local({
  node <- xml2::xml_find_first(doc, ".//*[contains(@class, 'author')]")
  if (!inherits(node, "xml_missing")) as_markdown(node) else NA_character_
})

# Packages the handout itself loads, plus the one its dataset lives in.
packages <- local({
  code <- paste(vapply(
    xml2::xml_find_all(doc, ".//pre|.//code"),
    function(n) xml2::xml_text(n),
    character(1)
  ), collapse = "\n")

  found <- regmatches(code, gregexpr("library\\(([A-Za-z0-9._]+)\\)", code))[[1]]
  found <- gsub("library\\(|\\)", "", found)

  if (grepl("nycflights13|\\bflights\\b", xml2::xml_text(doc))) {
    found <- c(found, "nycflights13")
  }
  found <- unique(found)
  if (length(found) == 0L) "tidyverse" else c("tidyverse", setdiff(found, "tidyverse"))
})

# ------------------------------------------------------------------- writing

slugify <- function(x) {
  x <- tolower(trimws(x))
  x <- gsub("[^a-z0-9]+", "-", x)
  gsub("^-|-$", "", x)
}

out <- c(
  "---",
  sprintf('title: "%s"', doc_title),
  'subtitle: "BDS Toolbox"',
  sprintf('author: "%s"', AUTHOR),
  "date: \"`r format(Sys.Date(), '%d %B %Y')`\"",
  "output:",
  "  html_document:",
  "    theme: cosmo",
  "    highlight: tango",
  "    toc: true",
  "    toc_depth: 3",
  "    toc_float:",
  "      collapsed: false",
  "    df_print: paged",
  "    code_download: true",
  "---",
  "",
  "```{r setup, include = FALSE}",
  "knitr::opts_chunk$set(",
  "  echo = TRUE,          # the hand-in has to show the code",
  "  message = FALSE,",
  "  warning = FALSE,",
  '  comment = "#>",',
  "  collapse = TRUE,",
  '  fig.align = "center",',
  "  fig.width = 6,",
  "  fig.height = 4,",
  "  dpi = 150",
  ")",
  "",
  "options(dplyr.summarise.inform = FALSE)",
  "set.seed(42)",
  "",
  sprintf("library(%s)", packages),
  "```",
  ""
)

# Intro: the handout's own framing, kept as a quote so it reads as source
# material rather than as your own words.
intro_lines <- character()
if (!is.na(doc_author)) intro_lines <- c(intro_lines, paste("Source:", doc_author))
for (b in intro_blocks) {
  if (!is.na(heading_level(b))) next
  if (node_name(b) == "pre") next   # already reflected in the setup chunk
  txt <- as_markdown(b)
  if (nzchar(txt)) intro_lines <- c(intro_lines, txt)
}
if (length(intro_lines) > 0L) {
  out <- c(out, paste(">", intro_lines), "")
}

fig_counter <- local({
  n <- 0L
  function() {
    n <<- n + 1L
    n
  }
})

n_chunks <- 0L

for (s in seq_along(section_start)) {
  head_txt <- headings[[section_start[[s]]]]
  slug <- slugify(head_txt)
  body <- if (section_end[[s]] > section_start[[s]]) {
    blocks[(section_start[[s]] + 1L):section_end[[s]]]
  } else {
    list()
  }

  out <- c(out, paste("##", head_txt), "")

  # A heading like "5.2.4: 1" is one question with lettered parts; a bare
  # "3.2.4" is a run of numbered questions.
  lettered <- grepl(":", head_txt)

  questions <- character()
  n_given <- 0L
  for (b in body) {
    nm <- node_name(b)

    imgs <- save_images(b, slug, fig_counter)
    for (img in imgs) {
      out <- c(out, sprintf("![](figures/%s){width=45%%}", img))
    }
    if (length(imgs) > 0L) out <- c(out, "")

    if (nm %in% c("ol", "ul")) {
      questions <- c(questions, list_items(b))
    } else if (nm == "pre") {
      code <- trimws(xml2::xml_text(b), which = "right")
      if (nzchar(trimws(code))) {
        code_lines <- strsplit(code, "\n", fixed = TRUE)[[1]]
        printed <- all(grepl("^\\s*##", code_lines))

        if (printed) {
          # The book's own printed output, not something to re-run.
          out <- c(out, "```", code, "```", "")
        } else {
          # Several code blocks in one exercise each need their own label.
          n_given <- n_given + 1L
          label <- if (n_given == 1L) {
            sprintf("ex-%s-given", slug)
          } else {
            sprintf("ex-%s-given-%d", slug, n_given)
          }
          n_chunks <- n_chunks + 1L
          out <- c(out, sprintf("```{r %s}", label), code, "```", "")
        }
      }
    } else {
      txt <- as_markdown(b)
      if (nzchar(txt)) questions <- c(questions, txt)
    }
  }

  if (length(questions) == 0L) questions <- "*See the handout.*"

  for (i in seq_along(questions)) {
    label <- if (length(questions) == 1L) {
      sprintf("ex-%s", slug)
    } else if (lettered) {
      sprintf("ex-%s%s", slug, letters[[i]])
    } else {
      sprintf("ex-%s-%d", slug, i)
    }

    marker <- if (length(questions) == 1L) {
      ""
    } else if (lettered) {
      sprintf("%s. ", letters[[i]])
    } else {
      sprintf("%d. ", i)
    }

    n_chunks <- n_chunks + 1L
    out <- c(
      out,
      sprintf("**%s%s**", marker, questions[[i]]),
      "",
      sprintf("```{r %s}", label),
      "",
      "```",
      ""
    )
  }
}

dir.create(dirname(target), recursive = TRUE, showWarnings = FALSE)
dir.create(fig_dir, recursive = TRUE, showWarnings = FALSE)

con <- file(target, open = "wb")
writeLines(enc2utf8(out), con, useBytes = TRUE)
close(con)

n_figs <- length(list.files(fig_dir))

message("Created ", target)
message("  ", length(section_start), " exercises, ", n_chunks, " chunks, ", n_figs, " figures")
message("  packages: ", paste(packages, collapse = ", "))
message("")
message("Read it through before you start -- then:")
message("  Rscript scripts/render.R ", id)
message("")
message("README row:")
message(sprintf(
  "| `%s` | %s |  | [Rmd](assignments/%s/%s.Rmd) | [HTML](output/%s.html) |",
  id, doc_title, id, id, id
))
