#!/usr/bin/env Rscript
# Knit assignments to self-contained HTML in output/, ready to hand in.
#
#   Rscript scripts/render.R              # every assignment
#   Rscript scripts/render.R 01-explore   # just one
#
# Run from the repository root. Each document is knitted in its own fresh R
# session with its own directory as the working directory, so an assignment
# that renders here will render anywhere.

# This code is generated by LLM.

if (!dir.exists("assignments")) {
  stop("Run this from the repository root (no 'assignments/' directory here).", call. = FALSE)
}

# An assignment whose YAML says `render_locally: false` is knitted somewhere
# else (e.g. a course server that can reach a database we cannot), and its
# committed HTML is the real hand-in. Never overwrite it from here.
renders_locally <- function(id) {
  rmd <- file.path("assignments", id, paste0(id, ".Rmd"))
  meta <- rmarkdown::yaml_front_matter(rmd)
  !identical(meta$render_locally, FALSE)
}

ids <- commandArgs(trailingOnly = TRUE)

if (length(ids) == 0L) {
  ids <- list.dirs("assignments", full.names = FALSE, recursive = FALSE)
  ids <- ids[!startsWith(ids, "_")]
  ids <- sort(ids[file.exists(file.path("assignments", ids, paste0(ids, ".Rmd")))])
}
if (length(ids) == 0L) {
  stop("No assignments found in 'assignments/'.", call. = FALSE)
}

skipped <- ids[!vapply(ids, renders_locally, logical(1))]
ids <- setdiff(ids, skipped)

for (id in skipped) {
  message("Skipping ", id, " (render_locally: false -- knitted elsewhere, ",
          "output/", id, ".html left untouched)")
}
if (length(ids) == 0L) {
  message("\nNothing to render.")
  quit(save = "no")
}

dir.create("output", showWarnings = FALSE)

for (id in ids) {
  rmd <- file.path("assignments", id, paste0(id, ".Rmd"))
  if (!file.exists(rmd)) {
    stop("No document found at '", rmd, "'.", call. = FALSE)
  }

  rmarkdown::render(
    input = rmd,
    output_file = paste0(id, ".html"),
    output_dir = normalizePath("output"),
    knit_root_dir = normalizePath(dirname(rmd)),
    envir = new.env(parent = globalenv())
  )
}

message("\nRendered to output/:")
for (id in ids) message("  ", id, ".html")
