#!/usr/bin/env Rscript
# Knit assignments to self-contained HTML in output/, ready to hand in.
#
#   Rscript scripts/render.R              # every assignment
#   Rscript scripts/render.R 01-explore   # just one
#
# Run from the repository root. Each document is knitted in its own fresh R
# session with its own directory as the working directory, so an assignment
# that renders here will render anywhere.

# This code is generated by LLM.

if (!dir.exists("assignments")) {
  stop("Run this from the repository root (no 'assignments/' directory here).", call. = FALSE)
}

ids <- commandArgs(trailingOnly = TRUE)

if (length(ids) == 0L) {
  ids <- list.dirs("assignments", full.names = FALSE, recursive = FALSE)
  ids <- ids[!startsWith(ids, "_")]
  ids <- sort(ids[file.exists(file.path("assignments", ids, paste0(ids, ".Rmd")))])
}
if (length(ids) == 0L) {
  stop("No assignments found in 'assignments/'.", call. = FALSE)
}

dir.create("output", showWarnings = FALSE)

for (id in ids) {
  rmd <- file.path("assignments", id, paste0(id, ".Rmd"))
  if (!file.exists(rmd)) {
    stop("No document found at '", rmd, "'.", call. = FALSE)
  }

  rmarkdown::render(
    input = rmd,
    output_file = paste0(id, ".html"),
    output_dir = normalizePath("output"),
    knit_root_dir = normalizePath(dirname(rmd)),
    envir = new.env(parent = globalenv())
  )
}

message("\nRendered to output/:")
for (id in ids) message("  ", id, ".html")
